# Documentation and testing purposes only #

[ISSUER]
attestation_of_reserve = ""
# affiliate_selling = false
blue_sky.states = ["NC", "GA", "NY", "DE", "FL"]
blue_sky.exchange = "None"
conditions = "Fully paid and non-assessable shares."
corporate_affiliations = []
ein = 123456789
highest_curr_solicitation = "Reg D"
intra_state = false
ir.email = ""
ir.phone = 0
jurisdiction.country = "US"
jurisdiction.subdivision = "DE"
latest_financial_balance_sheet = "https://issuers.info/0/...pdf"
latest_PNL_and_retained_earnings = "https://issuers.info/0/...pdf"
lockout_periods = [{start = "12-31", end = "4-15"}]
min_506c_state_init_usd = 5000
meetings = {2023 = "2023-4-29", 2024 = "endCountProxyVotesDate", 2024a = "2024-7-8"}
name = "Example Security Inc."
name_previous = ["Alias 1 (DE)", "Alias 2 (DE)", "Alias 3 Inc (WY)"]
over_10M_assets = false
principal_executive_office = "123 Main Street, Atlanta, GA 30000"
principal_place_of_business = "123 Main Street, Atlanta, GA 30000"
registration_effective = false
reporting_company = false
req_506b_ppm = false
shell_company = false
sic = 7374
transfer_agent = "BlockTrans Syndicate (99 Wall St #4640, New York, NY 10005)"

[ISSUER.desc]
main = "Example Company is used interally for product demos and development."
business = "Manufacturing and distribution of widgets."
facilities = "Remote-first business with shared offices in Atlanta, GA."
products = "Sells widgets."

[[ISSUER.meetings]]
meetingData = 2

[ACCOUNTS]
treasury = "GDRM3MK6KMHSYIT4E2AG2S2LWTDBJNYXE4H72C7YTTRWOWX5ZBECFWO7"
dspp = "GA777CHILD777TEST777ACCOUNT777DEMO777ISSUER777KY4LAZQZVA"
# reg.a.1.offering = ""
# reg.a.2.offering = ""
# reg.cf.offering = ""
# reg.d.506b.offering = ""
# reg.d.506c.offering = ""
# initial.offering = ""
# shelf.offering = ""
# reserved.701.benefit.plan = ""
# reserved.s3.benefit.plan = ""

[[INSIDERS]]
name = "John Doe"
title = "CEO"

[[INSIDERS]]
name = "Matt Smith"
title = "CFO"

[[STOCKS]]
authorized = 100000000
bankruptcy_preference = 3
code = "DEMO"
class = "A"
class_type = "common"
convertible = ""
cusip = ""
dividend = "None planned."
outstanding_EOFY = {2023-12-31 = 3248903}
par = "$0.001"
splits_effective = "1 to 5 effective 2021-4-20|3 to 2 effective 2021-10-9|2->1 effective 2022-1-1"
status = "test"
votes_per_share = 1

[[STOCKS]]
authorized = 70000
bankruptcy_preference = 2
code = "DEMOP"
class = "B"
class_type = "preffered"
convertible = "1->42 convertable to Class A."
cusip = ""
dividend = "Expected but not obligatory 3% dividend (non-cumulative)."
outstanding_EOFY = {2023-12-31 = 3248903}
par = "$0.001"
rights = "Same rights as 42 shares of Class A common stock, except for the voting rights of 10 Class A shares."
status = "test"
votes_per_share = 10

[[STOCKS.splits]]
effective = "2021-4-20"
before = 2
after = 3

[[STOCKS.splits]]
effective = "2021-10-9"
before = 3
after = 2

[[STOCKS.splits]]
effective = "2022-1-1"
before = 2
after = 1

[[STOCKS]]
authorized = 70000
bankruptcy_preference = 3
code = "DEMOA1"
class = "C"
class_type = "common"
convertible = "1->1 convertable to class A upon exchange listing."
cusip = ""
dividend = "Expected but not obligatory 3% dividend (non-cumulative)."
outstanding_EOFY = {2023-12-31 = 3248903}
par = "$0.001"
rights = "A share of Class B preffered stock has the rights of 1500 shares of Class A common stock, except that a Class B share has the voting rights of 10 Class A shares."
# reg_A_tier_2_yr_1_affiliated_sales_max_usd = "" -- todo: simplify reg a resales
status = "test"
votes_per_share = 1

[[BONDS]]
bankruptcy_preference = 1
code = "DEMOX1"
convertible = false
coupon_bps = 295
cusip = ""
maturity = "2023-10-4"
outstanding_EOFY = {2023-12-31 = 3248903}
par = ""
puttable = ""
status = "test"
