# Current information #

[ISSUER]
attestation_of_reserve = "https://blocktransfer.com/board-resolutions/1984803.pdf"
blue_sky.states = []
blue_sky.exchange = "None"
ir.email = "support@laylorcorporation.com"
ir.phone = "+16504657193"
jurisdiction.country = "US"
jurisdiction.subdivision = "SC"
logo = "https://blocktransfer.com/imgs/logos/1984803.png"
min_506c_state_init_usd = 5000
name = "Laylor Corporation"
registration_effective = false
reporting_company = false
req_506b_ppm = true
webpage = "https://laylorcorporation.com/"

[ISSUER.description]
main = "Laylor Corporation is a billion-dollar tech startup company that operates as a business development accelerator and multi-industry conglomerate. Laylor Corporation specializes in providing support to small and minority-owned businesses, with a specific focus on empowering individuals from diverse backgrounds, including people of color, impoverished communities, women, veterans, and individuals with disabilities. Their primary objective is to assist entrepreneurs in accessing the resources they need to bring their innovative ideas to fruition. With a strong emphasis on advertising and marketing, Laylor Corporation enables companies to expand their global reach. Their areas of expertise encompass investment management, cutting-edge programs, seamless payment solutions, secure financial transactions, cryptocurrency and blockchain investments, artificial intelligence, software technology, app development, and clean energy initiatives. Laylor Corporation is committed to fostering inclusive growth, driving technological advancements, and promoting a sustainable future in the business world."
business = "Laylor Corporation is a prominent tech company offering comprehensive business services and specializing in the development of innovative app platforms."
facilities = "Laylor Corporation operates with a virtual business office model, where employees work remotely from personal offices located in their homes."
products = "Laylor Corporation primarily engages in consulting and investment in research and development services, providing expertise and support to businesses in innovative projects and initiatives."
sic = 7380

[ISSUER.compliance]
ein = 861945850
highest_curr_solicitation = "None"
intra_state = false
latest_financial_balance_sheet = "https://issuers.info/1984803/BAL/latest.pdf"
latest_PNL_and_retained_earnings = "https://issuers.info/1984803/PNL/latest.pdf"
over_10M_assets = false
predecessor_names = "None"
principal_executive_office = "1318 North Main Street #1170, Summerville, SC 29483"
principal_place_of_business = "1318 North Main Street #1170, Summerville, SC 29483"
shell_company = false
transfer_agent = "BlockTrans Syndicate (99 Wall St #4640, New York, NY 10005)"

[ACCOUNTS]
treasury = "Pending initial company documents." # GDWKOK2CYQ5OQFMATXMXR4AEW6W5M4WZCFWS5DJP66YGXHBYQZLAYLOR
reg.d.506b.offering = "Pending initial company documents."

[[INSIDERS]]
name = "Tammy Harris"
title = "Director, President and Chairwoman"

[[INSIDERS]]
name = "David Lengua"
title = "Director, Chief Sound Officer"

[[INSIDERS]]
name = "Tivona Champayne"
title = "Director, Chief Design Officer"

[[INSIDERS]]
name = "Alana Abner"
title = "Director, Chief Fashion Officer"

[[INSIDERS]]
name = "Stacy Lee"
title = "Chief Risk Officer"

[[INSIDERS]]
name = "Lilly Galvez"
title = "Chief Financial Officer and Human Resource Manager"

[[INSIDERS]]
name = "Sheyontay Henson"
title = "Director"

[[STOCKS]]
authorized = 100000000
bankruptcy_preference = 1
code = "LAYLOR"
class = "None"
class_type = "common"
dividend = "None planned."
outstanding_EOFY = {2022-12-31 = 100000000}
par = "None"
status = "live"
votes_per_share = 1
